backend:
  name: github
  repo: lisbon1231/nedvex-admin
  branch: master
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  - label: "Вакансии"
    name: "jobs" 
    folder: "content/job"
    create: true
    slug: "{{fields.id}}"
    sortable_fields: ['priority']
    fields:
    - { name: id, label: Id, widget: generateId }
    - { label: "Коллекция", name: "tags", widget: "hidden", default: "vacancies"}
    - { label: "Шаблон", name: "layout", widget: "hidden", default: "job.njk"}
    - { 
      label: "Категория",
      name: "category",
      widget: "relation",
      collection: "categories",
      search_fields: ["title"],
      value_field: "title",
      display_fields: ["title"],
      multiple: false
    }
    - { label: "Приоритет", name: "priority", widget: "select", options: [{ label: "Приоритетная", value: "1" }, { label: "Не приоритетная", value: "2" }], multiple: false}
    - { label: "Название вакансии", name: "title", widget: "string" }
    - { label: "Описание вакансии", name: "description", widget: "markdown" }
    - { label: "Город", name: "city", widget: "string" }
    - { label: "Зарплата", name: "salary", widget: "string", default: "Не указана" }
    - { label: "Требования", name: "requirements", widget: "list", allow_add: true, field: {label: 'Требование', name: requirement, widget: "string" } }
    - { label: "Условия", name: "conditions", widget: "list", allow_add: true, field: {label: 'Условие', name: requirement, widget: "string" } }
    - { label: "Обязаности", name: "responsibilities", widget: "list", allow_add: true, field: {label: 'Обязанность', name: requirement, widget: "string" } }
  - label: "Категории вакансий"
    name: "categories" 
    folder: "content/categories"
    create: true
    slug: "{{fields.id}}"
    fields:
    - { name: id, label: Id, widget: generateId }
    - { label: "Коллекция", name: "tags", widget: "hidden", default: "categories"}
    - { label: "Название категории", name: "title", widget: "string" }
